# Generated by Django 3.2.5 on 2021-08-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_funding_goal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='porduct',
            new_name='product',
        ),
    ]
