# Generated by Django 3.2.5 on 2021-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_auto_20210809_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='num',
        ),
        migrations.AddField(
            model_name='funding',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
