# Generated by Django 3.2.5 on 2021-08-09 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0008_auto_20210809_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinginfo',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_funding', to=settings.AUTH_USER_MODEL),
        ),
    ]
