# Generated by Django 3.2.5 on 2021-08-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0009_fundinginfo_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='card',
            field=models.CharField(choices=[('kB', '국민'), ('shinhan', '신한'), ('hana', '하나'), ('woori', '우리')], default='', max_length=10, verbose_name='카드사'),
        ),
        migrations.AddField(
            model_name='funding',
            name='card_num',
            field=models.IntegerField(default=0, verbose_name='카드번호'),
        ),
        migrations.AddField(
            model_name='funding',
            name='color',
            field=models.CharField(choices=[('nougat', 'nougat 누가'), ('stormy', 'stormy 스토미'), ('milk', 'milk 밀크'), ('pompom', 'pompom 폼폼')], default='', max_length=10, verbose_name='카드사'),
        ),
        migrations.AddField(
            model_name='funding',
            name='create_dt',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='CREATE DATE'),
        ),
    ]
