# Generated by Django 3.2.5 on 2021-08-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0010_auto_20210810_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ('-create_dt',)},
        ),
        migrations.AlterField(
            model_name='funding',
            name='card',
            field=models.CharField(choices=[('hana', '하나'), ('kB', '국민'), ('shinhan', '신한'), ('woori', '우리')], default='', max_length=10, verbose_name='카드사'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='color',
            field=models.CharField(choices=[('milk', 'milk 밀크'), ('nougat', 'nougat 누가'), ('stormy', 'stormy 스토미'), ('pompom', 'pompom 폼폼')], default='', max_length=10, verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='funding_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.fundinginfo', verbose_name='Funding Info.'),
        ),
    ]
