# Generated by Django 3.2.5 on 2021-08-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0011_auto_20210810_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='card',
            field=models.CharField(choices=[('kB', '국민'), ('hana', '하나'), ('shinhan', '신한'), ('woori', '우리')], default='', max_length=10, verbose_name='카드사'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='funding_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.fundinginfo', verbose_name='Funding Info.'),
        ),
    ]
