# Generated by Django 3.2.5 on 2021-08-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.IntegerField(default=0)),
                ('card', models.CharField(max_length=30)),
                ('card_num', models.IntegerField(default=0)),
            ],
        ),
    ]
