# Generated by Django 3.2.5 on 2021-08-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='create_dt',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='CREATE DATE'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='card',
            field=models.CharField(max_length=10),
        ),
    ]
