# Generated by Django 3.2.5 on 2021-08-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20210802_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
