# Generated by Django 3.2.5 on 2021-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20210803_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='card',
            field=models.CharField(choices=[('hana', '하나'), ('shinhan', '신한'), ('kB', '국민'), ('woori', '우리')], max_length=10, verbose_name='카드사'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='card_num',
            field=models.IntegerField(default=0, verbose_name='카드번호'),
        ),
    ]
